_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "6": 4.50.0.dev0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
adv_lambda:
    value: 0.4333888182896358
dropout:
    value: 0.16115198648289902
latent_dim:
    value: 200
lr:
    value: 0.00010246861032274142
num_latents:
    value: 61
