_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "6": 4.50.0.dev0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
adv_lambda:
    value: 0.3653460604585835
dropout:
    value: 0.39864549198193233
latent_dim:
    value: 160
lr:
    value: 0.0011124004512223634
num_latents:
    value: 49
